### ISSUE TITLE
Language customization 

### ISSUE THREAD

**Issue by DariosDjimado** [eladnava/mailgen#24]
Hi,
Currently it is possible to fully customize the fields to any language. But unfortunately there isn't a way to change that message :

>  If you're having trouble clicking the **"Another language"** button, copy and paste the URL below into your web browser.

  An idea ?

**Comment by eladnava** [comment]
Thanks for reporting this! 👍 

I'm actually considering removing that line entirely from the `default` theme file, since no other theme file has it, and since there actually shouldn't be any need for it since it's 2016, almost 2017, and I don't think there are any e-mail clients that lack support for `<a>` hyperlinks in HTML emails.

Does anyone think otherwise?

**Comment by vuchl** [comment]
>  and I don't think there are any e-mail clients that lack support for <a> hyperlinks in HTML emails anymore.

Yes. This would be a huge deal breaker. Outlook, Thunderbird, Lotus Notes, GroupWise and mobile Versions have full hyperlink support. The deletion is propably the simplest and cleanest way here.
